version: '3.7'

networks:
  monitoring:
    driver: bridge

services:
  jaeger:
    image: jaegertracing/all-in-one:1.39
    networks:
      - monitoring
    ports:
      - "16686:16686"
      - "14268:14268"

  prometheus:
    image: prom/prometheus
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
