name: build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 8.0.x

            - name: Install dependencies
              run: dotnet restore Phase*/*.sln
              shell: bash


            - name: Build
              run: |
                for sln in Phase*/*.sln; do
                  dotnet build "$sln" --configuration Release --no-restore
                done
              shell: bash
              
            - name: Test
              run: |
                for sln in Phase*/*.sln; do
                  dotnet test "$sln" --no-restore --verbosity normal --collect:"XPlat Code Coverage"
                done
              shell: bash
